#
# Contains the full stack of rtb4free (not including crosstalk, elk, mysql)
# Does contain zookeeper and kafka.
#

version: "3"

services:

  zookeeper:
    image: "jplock/zookeeper"
    ports:
      - "2181:2181"
    networks:
      - rtb_net

  kafka:
    image: "ches/kafka"
    environment:
      ZOOKEEPER_IP: "zookeeper"
    ports:
      - "9092:9092"
    networks:
      - rtb_net
    depends_on:
      - zookeeper

  zerospike:
    image: "xinghao/zerospike:v1.1"
    environment:
      BROKERLIST: "kafka:9092"
    ports:
      - "6000:6000"
      - "6001:6001"
      - "6002:6002"
      - "7001:7001"
    #volumes:
    #  - "./cache.db:/cache.db"
    networks:
      - rtb_net
    depends_on:
      - kafka
    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && sleep 1; ./zerospike"

  bidder:
    image: "xinghao/rtb4free:v1.1"
    environment:
      BROKERLIST: "kafka:9092"
      PUBSUB: "zerospike"
      BID: "13.237.142.236"
      #EXTERNAL: "http://localhost:8080"      
      EXTERNAL: "http://13.237.142.236:8080"
      ADMINPORT: "0"
      TRACE: "true"
      ACCOUNTING: "NONE"
      FREQGOV: "false"
      THROTTLE: "500"
    ports:
      - "8080:8080"
      - "8155:8155"
      - "7379:7379"
      - "7000:7000"
    volumes:
      - "./logs:/logs"
    # - "./database.json:/database.json"   
    # - "./payday.json:/Campaigns/payday.json"
    networks:
      - rtb_net
    depends_on:
      - kafka
      - zerospike
    restart: always
    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh zerospike:6002 -t 120 && sleep 1; ./rtb4free"
    #command:  bash -c "./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh zerospike:6000 -t 120 && sleep 1; ./rtb4free-jmx"


networks:
  rtb_net:
    external: true
